version: "3"

services:
  collector:
    container_name: etorox-collector
    build: .
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "100"
